# <center>Workshop AI-Day 2</center>

In [1]:
print('Hello world!')

Hello world!


In [2]:
1 + 1

2

-----------------------

## Python

In [3]:
# list
x = [1, 2, 3, 4, 5]

In [4]:
x

[1, 2, 3, 4, 5]

In [5]:
x = [1, 'dua', 3, 4, 'lima']

In [6]:
x

[1, 'dua', 3, 4, 'lima']

-------------

## Numpy

In [7]:
import numpy as np

In [8]:
x = [1, 2, 3, 4, 5]

In [9]:
x

[1, 2, 3, 4, 5]

In [10]:
type(x)

list

In [11]:
x_numpy = np.array(x)

In [12]:
type(x_numpy)

numpy.ndarray

### Dasar numpy

In [13]:
x_numpy

array([1, 2, 3, 4, 5])

In [14]:
# cek ukuran array
x_numpy.shape

(5,)

In [15]:
x = [
    [1, 2, 3],
    [4, 5, 6]
]

In [16]:
x

[[1, 2, 3], [4, 5, 6]]

In [17]:
x = np.array(x)

In [18]:
x.shape

(2, 3)

In [19]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x_numpy[0]

1

In [21]:
x_numpy[-1]

5

In [22]:
x_numpy.mean()

3.0

In [23]:
x_numpy.std()

1.4142135623730951

--------------------

## Pandas

In [24]:
# import package
import pandas as pd

In [25]:
# load dataset
df = pd.read_csv('dataset.csv')

In [26]:
# print data pada df
df

sepal.length  sepal.width  petal.length  petal.width    variety  label
0             5.1          3.5           1.4          0.2     Setosa      0
1             4.9          3.0           1.4          0.2     Setosa      0
2             4.7          3.2           1.3          0.2     Setosa      0
3             4.6          3.1           1.5          0.2     Setosa      0
4             5.0          3.6           1.4          0.2     Setosa      0
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  Virginica      2
146           6.3          2.5           5.0          1.9  Virginica      2
147           6.5          3.0           5.2          2.0  Virginica      2
148           6.2          3.4           5.4          2.3  Virginica      2
149           5.9          3.0           5.1          1.8  Virginica      2

[150 rows x 6 columns]

In [27]:
# cek tipe data masing2 kolom di df
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
label             int64
dtype: object

In [28]:
# print nama kolom pada df
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [29]:
# akses kolom sepal length
df['sepal.length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [30]:
# akses nilainya saja pada kolom sepal length
df['sepal.length'].values

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [31]:
# akses kolom semua atribut 
df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [32]:
# akses hanya nilai pada kolom semua atribut 
fitur = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values

In [33]:
# akses hanya nilai pada kolom label
label = df['label'].values

In [34]:
# ubah ke bentuk numpy array
x = np.array(fitur)
y = np.array(label)

In [35]:
x.shape

(150, 4)

In [36]:
y.shape

(150,)

----------------

## Training Model

In [37]:
from sklearn.preprocessing import StandardScaler

$$\frac{x-mean}{std}$$

### Cari informasi statistik dari atribut/fitur

untuk digunakan saat prediksi/klasifikasi data baru

In [38]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [39]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [40]:
atribut_mean = x.mean(axis=0)

In [41]:
atribut_std = x.std(axis=0)

### Normalisasi

In [42]:
x_norm = StandardScaler().fit_transform(x)

In [43]:
x_norm.shape

(150, 4)

In [44]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [45]:
x_norm

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

## Training

### train test split

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25, stratify=y, random_state=12)

In [48]:
x_train.shape

(112, 4)

In [49]:
x_test.shape

(38, 4)

In [50]:
150 * 0.25

37.5

### training neural network

In [51]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [52]:
# buat blueprint model
model = Sequential()
# tentukan layer per model
model.add(Dense(64, input_dim=4, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))
# tentukan loss, algoritma belajar, dan jenis evaluasi
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
# isi data ke network dan train
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 38ms/step - loss: 1.0511 - accuracy: 0.4196 - val_loss: 0.9715 - val_accuracy: 0.5789
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9698 - accuracy: 0.6875 - val_loss: 0.9064 - val_accuracy: 0.7105
Epoch 3/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8956 - accuracy: 0.7857 - val_loss: 0.8470 - val_accuracy: 0.7632
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8271 - accuracy: 0.7768 - val_loss: 0.7919 - val_accuracy: 0.7632
Epoch 5/100
4/4 [==============================] - 0s 6ms/step - loss: 0.7677 - accuracy: 0.7857 - val_loss: 0.7421 - val_accuracy: 0.7895
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.7113 - accuracy: 0.7946 - val_loss: 0.6981 - val_accuracy: 0.7895
Epoch 7/100
4/4 [==============================] - 0s 8ms/step - loss: 0.6631 - accuracy: 0.7946 - val_loss: 0.6577 - val_accuracy: 0.7895
Epoch 8/100
4/4 [=========

4/4 [==============================] - 0s 4ms/step - loss: 0.0723 - accuracy: 0.9911 - val_loss: 0.2464 - val_accuracy: 0.8947
Epoch 60/100
4/4 [==============================] - 0s 8ms/step - loss: 0.0698 - accuracy: 0.9911 - val_loss: 0.2428 - val_accuracy: 0.8947
Epoch 61/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0677 - accuracy: 0.9911 - val_loss: 0.2392 - val_accuracy: 0.8947
Epoch 62/100
4/4 [==============================] - 0s 6ms/step - loss: 0.0666 - accuracy: 0.9911 - val_loss: 0.2368 - val_accuracy: 0.8947
Epoch 63/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0642 - accuracy: 0.9911 - val_loss: 0.2299 - val_accuracy: 0.9211
Epoch 64/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0618 - accuracy: 0.9911 - val_loss: 0.2250 - val_accuracy: 0.9211
Epoch 65/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0603 - accuracy: 0.9911 - val_loss: 0.2216 - val_accuracy: 0.9211
Epoch 66/100
4/4 [===============

### Save model

In [54]:
model.save('model.h5')

### Load model

In [55]:
from tensorflow.keras.models import load_model

In [56]:
model = load_model('model.h5')

--------------------

## Prediction

### Prepare data & normalisasi

In [57]:
atribut_mean

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [58]:
atribut_std

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [59]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [60]:
df.iloc[100, :]

sepal.length          6.3
sepal.width           3.3
petal.length            6
petal.width           2.5
variety         Virginica
label                   2
Name: 100, dtype: object

$$\frac{x-mean}{std}$$

In [61]:
sepalLength = (6.3 - atribut_mean[0]) / atribut_std[0]
sepalWidth = (3.3 - atribut_mean[1]) / atribut_std[1]
petalLength = (6 - atribut_mean[2]) / atribut_std[2]
petalWidth = (2.5 - atribut_mean[3]) / atribut_std[3]

In [62]:
xPred = [[sepalLength, sepalWidth, petalLength, petalWidth]]

In [63]:
xPred

[[0.5533332750260068,
  0.5586108194543139,
  1.2742951114029821,
  1.7120959436691794]]

In [64]:
xPred = np.array(xPred)

### Prediction

In [65]:
hasil = model.predict(xPred)

In [66]:
hasil

array([[1.5938586e-07, 9.1606860e-05, 9.9990821e-01]], dtype=float32)

In [67]:
np.argmax(hasil, axis=1)

array([2], dtype=int64)